name: ci_dockerfile
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-19.04, debian-10, centos-7, centos-8]
        include:
          - os: ubuntu-18.04
            family: ubuntu
            version: 18.04
          - os: ubuntu-19.04
            family: ubuntu
            version: 19.04
          - os: debian-10
            family: debian
            version: 10
          - os: centos-7
            family: centos
            version: 7
          - os: centos-8
            family: centos
            version: 8
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          docker build -t fastide/bootstrap-${{ matrix.family }}:${{ matrix.version  }} --build-arg OS_FAMILY=${{ matrix.family }} --build-arg OS_VERSION=${{ matrix.version  }} .
          echo "${DOCKER_PASSWORD}" | docker login --username fastide --password-stdin
          docker push fastide/bootstrap-${{ matrix.family }}:${{ matrix.version  }}
